#!/usr/bin/env python3
"""
Fetch Cambridge MA real estate stats from Zillow Research public CSVs.
Outputs WP-CLI commands to update WordPress options on production.

Usage:
    python3 update_cambridge_stats.py           # print WP-CLI commands
    python3 update_cambridge_stats.py --json    # print JSON (for piping)

Data sources (public, no API key required):
    https://files.zillowstatic.com/research/public_csvs/
"""

import csv
import io
import json
import sys
import urllib.request
from datetime import datetime
from typing import Optional

# ── Zillow Research CSV URLs ──────────────────────────────────────────────────
# Verified working as of 2026-03.  Check https://www.zillow.com/research/data/
# if a URL starts returning 404 — Zillow occasionally renames files.
ZILLOW_CSVS = {
    "median_sale_price": (
        "https://files.zillowstatic.com/research/public_csvs/median_sale_price/"
        "City_median_sale_price_uc_sfrcondo_sm_sa_month.csv"
    ),
    "active_listings": (
        "https://files.zillowstatic.com/research/public_csvs/invt_fs/"
        "City_invt_fs_uc_sfrcondo_sm_month.csv"
    ),
    # Days on market public CSV removed by Zillow; kept as a key so fallback is used.
    # "days_on_market": None,  # Zillow no longer publishes this metric publicly
}

TARGET_CITY = "Cambridge"
TARGET_STATE = "MA"

# Fallback values (used if Zillow data is unavailable)
FALLBACKS = {
    "median_sale_price": "$1.2M",
    "active_listings": "45",
    "days_on_market": "28",
}


def fetch_csv(url: str) -> list:
    """Download a CSV from Zillow and return rows as a list of dicts."""
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        content = resp.read().decode("utf-8")
    reader = csv.DictReader(io.StringIO(content))
    return list(reader)


def get_latest_value(rows: list, city: str, state: str) -> Optional[float]:
    """
    Filter rows for the given city/state and return the most recent value.
    Zillow CSVs have columns: RegionName, StateName, ...date columns...
    """
    city_rows = [
        r for r in rows
        if r.get("RegionName", "").strip() == city
        and r.get("StateName", "").strip() == state
    ]
    if not city_rows:
        return None

    row = city_rows[0]

    # Date columns are ISO format YYYY-MM-DD; find the last non-empty one
    date_cols = sorted(
        [k for k in row if k.startswith("20") and len(k) == 10],
        reverse=True,
    )
    for col in date_cols:
        val = row.get(col, "").strip()
        if val:
            try:
                return float(val)
            except ValueError:
                continue
    return None


def format_price(value: float) -> str:
    """Format a dollar amount: $1.2M, $950K, etc."""
    if value >= 1_000_000:
        return f"${value / 1_000_000:.1f}M"
    elif value >= 1_000:
        return f"${value / 1_000:.0f}K"
    return f"${value:,.0f}"


def main() -> None:
    use_json = "--json" in sys.argv

    stats = {}
    errors = []

    # Seed fallbacks so all keys are always present
    for key, fallback in FALLBACKS.items():
        stats[key] = fallback

    for key, url in ZILLOW_CSVS.items():
        try:
            rows = fetch_csv(url)
            value = get_latest_value(rows, TARGET_CITY, TARGET_STATE)
            if value is None:
                raise ValueError(f"Cambridge MA not found in {key} data")

            if key == "median_sale_price":
                stats[key] = format_price(value)
            elif key == "active_listings":
                stats[key] = str(int(round(value)))
            elif key == "days_on_market":
                stats[key] = str(int(round(value)))
            else:
                stats[key] = str(value)

        except Exception as exc:
            errors.append(f"Warning: {key} — {exc} (using fallback)")
            stats[key] = FALLBACKS[key]

    # Add metadata
    stats["last_updated"] = datetime.utcnow().strftime("%Y-%m-%d")

    if errors:
        print("\n".join(errors), file=sys.stderr)

    if use_json:
        print(json.dumps(stats, indent=2))
        return

    # ── Output WP-CLI commands ─────────────────────────────────────────────
    wp_options = {
        "cambridge_stat_median_price":    stats["median_sale_price"],
        "cambridge_stat_active_listings": stats["active_listings"],
        "cambridge_stat_days_on_market":  stats["days_on_market"],
        "cambridge_stat_last_updated":    stats["last_updated"],
    }

    print("#!/bin/bash")
    print("# Auto-generated by update_cambridge_stats.py")
    print(f"# Data as of {stats['last_updated']} (UTC)")
    print()
    for option, value in wp_options.items():
        # Use --path to target the WordPress install directory
        print(
            f"wp option update '{option}' '{value}' --allow-root"
        )
    print()
    print("# Flush LiteSpeed Cache")
    print("wp litespeed-purge all --allow-root 2>/dev/null || true")
    print()
    print(f"echo 'Cambridge stats updated: {json.dumps(stats)}'")


if __name__ == "__main__":
    main()
